### ISSUE TITLE
Where comes the d3 dependency name from

### ISSUE THREAD

**Issue by jirihelmich** [tobice/d3-ldvm-pipeline#1]
I had to change it from `d3` to d3js to make it work with webjars. I could write a shim for require, I just want to know if you made it up, since I believe that it should be `d3js`.

**Comment by tobice** [comment]
I might be a bit confused here. You are talking about the external dependency [here](https://github.com/tobice/d3-ldvm-pipeline/blob/master/webpack/build.js#L17)?

Well, the library is called [`d3`](https://www.npmjs.com/package/d3) but apart from that, I used it simply because this way it [works](https://github.com/tobice/d3-ldvm-pipeline/blob/master/example/index.html) with the standard distributed d3 file. 

It seems that the `js` suffix is added in the [webjar](https://github.com/webjars/d3js/blob/master/pom.xml).

**Comment by jirihelmich** [comment]
The newer one has shim for d3 as well, OK, let's close this one as well.

st 2. 9. 2015 v 18:30 odesílatel Tobiáš Potoček notifications@github.com
napsal:
